### ISSUE TITLE
升级nodejs 4.0 版本 路由请求基本上都不能用了求解

### ISSUE THREAD

**Issue by Messilimeng** [ckken/KNode#19]
所有的请求都指向首页 其他页面都进不去了

**Comment by ckken** [comment]
更新下路由试试

**Comment by ckken** [comment]
有兴趣可以使用我的V2版本 很不错(⊙o⊙)哦

**Comment by Messilimeng** [comment]
@ckken 你不是不用koa了吗 不是说什么内存泄漏严重什么的吗  一天到捣腾

**Comment by ckken** [comment]
V2 不用koa 啊 用express· 看看 https://github.com/ckken/KNode/tree/v2

**Comment by Messilimeng** [comment]
@ckken  express 随便怎么捣腾 我现在就像看看有什么好的koa 的项目解决方案

**Comment by ckken** [comment]
express es7版本 比 koa 要方便N倍 你没看过 这么块下定论真的好么

**Comment by Messilimeng** [comment]
@ckken 嘿嘿 我刚才看了你一下你的 代码  还真是有es7 我还以你用那个sync 那个插件的呢 我 有空看看 加你一下 qq 你能瘦的了？

**Comment by ckken** [comment]
117692258

**Comment by Messilimeng** [comment]
@ckken 你的真实姓名是什么

**Comment by ckken** [comment]
许宏斌
